### ISSUE TITLE
Can't save 

### ISSUE THREAD

**Issue by KHeresy** [aParr0t/agario-custom-skin#1]
Hi.

I tried to follow your step to upload my image.
The image can be shown in editor.

But after I press the  "save", and enter the name to save.

![image](https://user-images.githubusercontent.com/1277610/204138586-f4135bea-1046-4207-846a-e2f596c2a5b6.png)

It will just return to initial page without save anything.

Do I miss something?

**Comment by aParr0t** [comment]
Hi, sorry for late response.
I'm also having the same issue as you. I don't know how to fix it. It did work a couple of months ago when I released this trick. Maybe they've patched it?

**Comment by KHeresy** [comment]
It is so sad to hear this. :'(

**Comment by aParr0t** [comment]
Agree. This was my first time making something that others could benefit from. Thank you for trying it out, and I'm sorry it didn't work out.

**Comment by aParr0t** [comment]
Hi. I'm not sure if it's still important to you, but it worked for me today. I managed to create a custom skin from an image I found. A weird error happened at step 7 where I got the text "undefined" after hitting enter. I solved it blindly by repeating step 7 (pasting the code into the console and hitting enter). Give it a try if you want to.

**Comment by KHeresy** [comment]
It still not works for me :'(

I got `undefined` too, but run script twice not help.

At step 9, the image will rstore as defualt and save nothing in my case.
